/*add additional fields for having a DV represent a pattern value in EPANET - 1 for each period of the day*/

/****** Object:  Table [dbo].[tlkpEPANETFieldDictionary]    Script Date: 3/7/2016 1:21:59 PM ******/

Delete from tlkpEPANETFieldDictionary where FieldName in ('Multipliers1','Multipliers2','Multipliers3','Multipliers4','Multipliers5','Multipliers6') and tablename_fk = 11;



SET IDENTITY_INSERT [tlkpEPANETFieldDictionary] ON
Go

INSERT [dbo].[tlkpEPANETFieldDictionary] ([ID], [TableName_FK], [FieldName], [FieldAlias], [InINP], [FieldINP_Number], [Subtype], [CanBeDV], [FieldClass], [VarOptionList_FK], [IsLookupList], [API_Update], [EPANET_CSharp_LibInt], [RowNo]) VALUES (286, 11, N'Period1Multiplier', N'Period1Multiplier', 1, 2, NULL, 0, 4, 0, 0, 0, NULL, 1);
INSERT [dbo].[tlkpEPANETFieldDictionary] ([ID], [TableName_FK], [FieldName], [FieldAlias], [InINP], [FieldINP_Number], [Subtype], [CanBeDV], [FieldClass], [VarOptionList_FK], [IsLookupList], [API_Update], [EPANET_CSharp_LibInt], [RowNo]) VALUES (287, 11, N'Period2Multiplier', N'Period2Multiplier', 1, 3, NULL, 0, 4, 0, 0, 0, NULL, 1);
INSERT [dbo].[tlkpEPANETFieldDictionary] ([ID], [TableName_FK], [FieldName], [FieldAlias], [InINP], [FieldINP_Number], [Subtype], [CanBeDV], [FieldClass], [VarOptionList_FK], [IsLookupList], [API_Update], [EPANET_CSharp_LibInt], [RowNo]) VALUES (288, 11, N'Period3Multiplier', N'Period3Multiplier', 1, 4, NULL, 0, 4, 0, 0, 0, NULL, 1);
INSERT [dbo].[tlkpEPANETFieldDictionary] ([ID], [TableName_FK], [FieldName], [FieldAlias], [InINP], [FieldINP_Number], [Subtype], [CanBeDV], [FieldClass], [VarOptionList_FK], [IsLookupList], [API_Update], [EPANET_CSharp_LibInt], [RowNo]) VALUES (289, 11, N'Period4Multiplier', N'Period4Multiplier', 1, 5, NULL, 0, 4, 0, 0, 0, NULL, 1);
INSERT [dbo].[tlkpEPANETFieldDictionary] ([ID], [TableName_FK], [FieldName], [FieldAlias], [InINP], [FieldINP_Number], [Subtype], [CanBeDV], [FieldClass], [VarOptionList_FK], [IsLookupList], [API_Update], [EPANET_CSharp_LibInt], [RowNo]) VALUES (290, 11, N'Period5Multiplier', N'Period5Multiplier', 1, 6, NULL, 0, 4, 0, 0, 0, NULL, 1);
INSERT [dbo].[tlkpEPANETFieldDictionary] ([ID], [TableName_FK], [FieldName], [FieldAlias], [InINP], [FieldINP_Number], [Subtype], [CanBeDV], [FieldClass], [VarOptionList_FK], [IsLookupList], [API_Update], [EPANET_CSharp_LibInt], [RowNo]) VALUES (291, 11, N'Period6Multiplier', N'Period6Multiplier', 1, 7, NULL, 0, 4, 0, 0, 0, NULL, 1);
INSERT [dbo].[tlkpEPANETFieldDictionary] ([ID], [TableName_FK], [FieldName], [FieldAlias], [InINP], [FieldINP_Number], [Subtype], [CanBeDV], [FieldClass], [VarOptionList_FK], [IsLookupList], [API_Update], [EPANET_CSharp_LibInt], [RowNo]) VALUES (363, 11, N'Period7Multiplier', N'Period7Multiplier', 1, 2, NULL, 0, 4, 0, 0, 0, NULL, 2);
INSERT [dbo].[tlkpEPANETFieldDictionary] ([ID], [TableName_FK], [FieldName], [FieldAlias], [InINP], [FieldINP_Number], [Subtype], [CanBeDV], [FieldClass], [VarOptionList_FK], [IsLookupList], [API_Update], [EPANET_CSharp_LibInt], [RowNo]) VALUES (364, 11, N'Period8Multiplier', N'Period8Multiplier', 1, 3, NULL, 0, 4, 0, 0, 0, NULL, 2);
INSERT [dbo].[tlkpEPANETFieldDictionary] ([ID], [TableName_FK], [FieldName], [FieldAlias], [InINP], [FieldINP_Number], [Subtype], [CanBeDV], [FieldClass], [VarOptionList_FK], [IsLookupList], [API_Update], [EPANET_CSharp_LibInt], [RowNo]) VALUES (365, 11, N'Period9Multiplier', N'Period9Multiplier', 1, 4, NULL, 0, 4, 0, 0, 0, NULL, 2);
INSERT [dbo].[tlkpEPANETFieldDictionary] ([ID], [TableName_FK], [FieldName], [FieldAlias], [InINP], [FieldINP_Number], [Subtype], [CanBeDV], [FieldClass], [VarOptionList_FK], [IsLookupList], [API_Update], [EPANET_CSharp_LibInt], [RowNo]) VALUES (366, 11, N'Period10Multiplier', N'Period10Multiplier', 1, 5, NULL, 0, 4, 0, 0, 0, NULL, 2);
INSERT [dbo].[tlkpEPANETFieldDictionary] ([ID], [TableName_FK], [FieldName], [FieldAlias], [InINP], [FieldINP_Number], [Subtype], [CanBeDV], [FieldClass], [VarOptionList_FK], [IsLookupList], [API_Update], [EPANET_CSharp_LibInt], [RowNo]) VALUES (367, 11, N'Period11Multiplier', N'Period11Multiplier', 1, 6, NULL, 0, 4, 0, 0, 0, NULL, 2);
INSERT [dbo].[tlkpEPANETFieldDictionary] ([ID], [TableName_FK], [FieldName], [FieldAlias], [InINP], [FieldINP_Number], [Subtype], [CanBeDV], [FieldClass], [VarOptionList_FK], [IsLookupList], [API_Update], [EPANET_CSharp_LibInt], [RowNo]) VALUES (368, 11, N'Period12Multiplier', N'Period12Multiplier', 1, 7, NULL, 0, 4, 0, 0, 0, NULL, 2);
INSERT [dbo].[tlkpEPANETFieldDictionary] ([ID], [TableName_FK], [FieldName], [FieldAlias], [InINP], [FieldINP_Number], [Subtype], [CanBeDV], [FieldClass], [VarOptionList_FK], [IsLookupList], [API_Update], [EPANET_CSharp_LibInt], [RowNo]) VALUES (369, 11, N'Period13Multiplier', N'Period13Multiplier', 1, 2, NULL, 0, 4, 0, 0, 0, NULL, 3);
INSERT [dbo].[tlkpEPANETFieldDictionary] ([ID], [TableName_FK], [FieldName], [FieldAlias], [InINP], [FieldINP_Number], [Subtype], [CanBeDV], [FieldClass], [VarOptionList_FK], [IsLookupList], [API_Update], [EPANET_CSharp_LibInt], [RowNo]) VALUES (370, 11, N'Period14Multiplier', N'Period14Multiplier', 1, 3, NULL, 0, 4, 0, 0, 0, NULL, 3);
INSERT [dbo].[tlkpEPANETFieldDictionary] ([ID], [TableName_FK], [FieldName], [FieldAlias], [InINP], [FieldINP_Number], [Subtype], [CanBeDV], [FieldClass], [VarOptionList_FK], [IsLookupList], [API_Update], [EPANET_CSharp_LibInt], [RowNo]) VALUES (371, 11, N'Period15Multiplier', N'Period15Multiplier', 1, 4, NULL, 0, 4, 0, 0, 0, NULL, 3);
INSERT [dbo].[tlkpEPANETFieldDictionary] ([ID], [TableName_FK], [FieldName], [FieldAlias], [InINP], [FieldINP_Number], [Subtype], [CanBeDV], [FieldClass], [VarOptionList_FK], [IsLookupList], [API_Update], [EPANET_CSharp_LibInt], [RowNo]) VALUES (372, 11, N'Period16Multiplier', N'Period16Multiplier', 1, 5, NULL, 0, 4, 0, 0, 0, NULL, 3);
INSERT [dbo].[tlkpEPANETFieldDictionary] ([ID], [TableName_FK], [FieldName], [FieldAlias], [InINP], [FieldINP_Number], [Subtype], [CanBeDV], [FieldClass], [VarOptionList_FK], [IsLookupList], [API_Update], [EPANET_CSharp_LibInt], [RowNo]) VALUES (373, 11, N'Period17Multiplier', N'Period17Multiplier', 1, 6, NULL, 0, 4, 0, 0, 0, NULL, 3);
INSERT [dbo].[tlkpEPANETFieldDictionary] ([ID], [TableName_FK], [FieldName], [FieldAlias], [InINP], [FieldINP_Number], [Subtype], [CanBeDV], [FieldClass], [VarOptionList_FK], [IsLookupList], [API_Update], [EPANET_CSharp_LibInt], [RowNo]) VALUES (374, 11, N'Period18Multiplier', N'Period18Multiplier', 1, 7, NULL, 0, 4, 0, 0, 0, NULL, 3);
INSERT [dbo].[tlkpEPANETFieldDictionary] ([ID], [TableName_FK], [FieldName], [FieldAlias], [InINP], [FieldINP_Number], [Subtype], [CanBeDV], [FieldClass], [VarOptionList_FK], [IsLookupList], [API_Update], [EPANET_CSharp_LibInt], [RowNo]) VALUES (375, 11, N'Period19Multiplier', N'Period19Multiplier', 1, 2, NULL, 0, 4, 0, 0, 0, NULL, 4);
INSERT [dbo].[tlkpEPANETFieldDictionary] ([ID], [TableName_FK], [FieldName], [FieldAlias], [InINP], [FieldINP_Number], [Subtype], [CanBeDV], [FieldClass], [VarOptionList_FK], [IsLookupList], [API_Update], [EPANET_CSharp_LibInt], [RowNo]) VALUES (376, 11, N'Period20Multiplier', N'Period20Multiplier', 1, 3, NULL, 0, 4, 0, 0, 0, NULL, 4);
INSERT [dbo].[tlkpEPANETFieldDictionary] ([ID], [TableName_FK], [FieldName], [FieldAlias], [InINP], [FieldINP_Number], [Subtype], [CanBeDV], [FieldClass], [VarOptionList_FK], [IsLookupList], [API_Update], [EPANET_CSharp_LibInt], [RowNo]) VALUES (377, 11, N'Period21Multiplier', N'Period21Multiplier', 1, 4, NULL, 0, 4, 0, 0, 0, NULL, 4);
INSERT [dbo].[tlkpEPANETFieldDictionary] ([ID], [TableName_FK], [FieldName], [FieldAlias], [InINP], [FieldINP_Number], [Subtype], [CanBeDV], [FieldClass], [VarOptionList_FK], [IsLookupList], [API_Update], [EPANET_CSharp_LibInt], [RowNo]) VALUES (378, 11, N'Period22Multiplier', N'Period22Multiplier', 1, 5, NULL, 0, 4, 0, 0, 0, NULL, 4);
INSERT [dbo].[tlkpEPANETFieldDictionary] ([ID], [TableName_FK], [FieldName], [FieldAlias], [InINP], [FieldINP_Number], [Subtype], [CanBeDV], [FieldClass], [VarOptionList_FK], [IsLookupList], [API_Update], [EPANET_CSharp_LibInt], [RowNo]) VALUES (379, 11, N'Period23Multiplier', N'Period23Multiplier', 1, 6, NULL, 0, 4, 0, 0, 0, NULL, 4);
INSERT [dbo].[tlkpEPANETFieldDictionary] ([ID], [TableName_FK], [FieldName], [FieldAlias], [InINP], [FieldINP_Number], [Subtype], [CanBeDV], [FieldClass], [VarOptionList_FK], [IsLookupList], [API_Update], [EPANET_CSharp_LibInt], [RowNo]) VALUES (380, 11, N'Period24Multiplier', N'Period24Multiplier', 1, 7, NULL, 0, 4, 0, 0, 0, NULL, 4);
INSERT [dbo].[tlkpEPANETFieldDictionary] ([ID], [TableName_FK], [FieldName], [FieldAlias], [InINP], [FieldINP_Number], [Subtype], [CanBeDV], [FieldClass], [VarOptionList_FK], [IsLookupList], [API_Update], [EPANET_CSharp_LibInt], [RowNo]) VALUES (381, 11, N'Period25Multiplier', N'Period25Multiplier', 1, 2, NULL, 0, 4, 0, 0, 0, NULL, 5);
INSERT [dbo].[tlkpEPANETFieldDictionary] ([ID], [TableName_FK], [FieldName], [FieldAlias], [InINP], [FieldINP_Number], [Subtype], [CanBeDV], [FieldClass], [VarOptionList_FK], [IsLookupList], [API_Update], [EPANET_CSharp_LibInt], [RowNo]) VALUES (382, 11, N'Period26Multiplier', N'Period26Multiplier', 1, 3, NULL, 0, 4, 0, 0, 0, NULL, 5);
INSERT [dbo].[tlkpEPANETFieldDictionary] ([ID], [TableName_FK], [FieldName], [FieldAlias], [InINP], [FieldINP_Number], [Subtype], [CanBeDV], [FieldClass], [VarOptionList_FK], [IsLookupList], [API_Update], [EPANET_CSharp_LibInt], [RowNo]) VALUES (383, 11, N'Period27Multiplier', N'Period27Multiplier', 1, 4, NULL, 0, 4, 0, 0, 0, NULL, 5);
INSERT [dbo].[tlkpEPANETFieldDictionary] ([ID], [TableName_FK], [FieldName], [FieldAlias], [InINP], [FieldINP_Number], [Subtype], [CanBeDV], [FieldClass], [VarOptionList_FK], [IsLookupList], [API_Update], [EPANET_CSharp_LibInt], [RowNo]) VALUES (384, 11, N'Period28Multiplier', N'Period28Multiplier', 1, 5, NULL, 0, 4, 0, 0, 0, NULL, 5);
INSERT [dbo].[tlkpEPANETFieldDictionary] ([ID], [TableName_FK], [FieldName], [FieldAlias], [InINP], [FieldINP_Number], [Subtype], [CanBeDV], [FieldClass], [VarOptionList_FK], [IsLookupList], [API_Update], [EPANET_CSharp_LibInt], [RowNo]) VALUES (385, 11, N'Period29Multiplier', N'Period29Multiplier', 1, 6, NULL, 0, 4, 0, 0, 0, NULL, 5);
INSERT [dbo].[tlkpEPANETFieldDictionary] ([ID], [TableName_FK], [FieldName], [FieldAlias], [InINP], [FieldINP_Number], [Subtype], [CanBeDV], [FieldClass], [VarOptionList_FK], [IsLookupList], [API_Update], [EPANET_CSharp_LibInt], [RowNo]) VALUES (386, 11, N'Period30Multiplier', N'Period30Multiplier', 1, 7, NULL, 0, 4, 0, 0, 0, NULL, 5);
INSERT [dbo].[tlkpEPANETFieldDictionary] ([ID], [TableName_FK], [FieldName], [FieldAlias], [InINP], [FieldINP_Number], [Subtype], [CanBeDV], [FieldClass], [VarOptionList_FK], [IsLookupList], [API_Update], [EPANET_CSharp_LibInt], [RowNo]) VALUES (387, 11, N'Period31Multiplier', N'Period31Multiplier', 1, 2, NULL, 0, 4, 0, 0, 0, NULL, 6);
INSERT [dbo].[tlkpEPANETFieldDictionary] ([ID], [TableName_FK], [FieldName], [FieldAlias], [InINP], [FieldINP_Number], [Subtype], [CanBeDV], [FieldClass], [VarOptionList_FK], [IsLookupList], [API_Update], [EPANET_CSharp_LibInt], [RowNo]) VALUES (388, 11, N'Period32Multiplier', N'Period32Multiplier', 1, 3, NULL, 0, 4, 0, 0, 0, NULL, 6);
INSERT [dbo].[tlkpEPANETFieldDictionary] ([ID], [TableName_FK], [FieldName], [FieldAlias], [InINP], [FieldINP_Number], [Subtype], [CanBeDV], [FieldClass], [VarOptionList_FK], [IsLookupList], [API_Update], [EPANET_CSharp_LibInt], [RowNo]) VALUES (389, 11, N'Period33Multiplier', N'Period33Multiplier', 1, 4, NULL, 0, 4, 0, 0, 0, NULL, 6);
INSERT [dbo].[tlkpEPANETFieldDictionary] ([ID], [TableName_FK], [FieldName], [FieldAlias], [InINP], [FieldINP_Number], [Subtype], [CanBeDV], [FieldClass], [VarOptionList_FK], [IsLookupList], [API_Update], [EPANET_CSharp_LibInt], [RowNo]) VALUES (390, 11, N'Period34Multiplier', N'Period34Multiplier', 1, 5, NULL, 0, 4, 0, 0, 0, NULL, 6);
INSERT [dbo].[tlkpEPANETFieldDictionary] ([ID], [TableName_FK], [FieldName], [FieldAlias], [InINP], [FieldINP_Number], [Subtype], [CanBeDV], [FieldClass], [VarOptionList_FK], [IsLookupList], [API_Update], [EPANET_CSharp_LibInt], [RowNo]) VALUES (391, 11, N'Period35Multiplier', N'Period35Multiplier', 1, 6, NULL, 0, 4, 0, 0, 0, NULL, 6);
INSERT [dbo].[tlkpEPANETFieldDictionary] ([ID], [TableName_FK], [FieldName], [FieldAlias], [InINP], [FieldINP_Number], [Subtype], [CanBeDV], [FieldClass], [VarOptionList_FK], [IsLookupList], [API_Update], [EPANET_CSharp_LibInt], [RowNo]) VALUES (392, 11, N'Period36Multiplier', N'Period36Multiplier', 1, 7, NULL, 0, 4, 0, 0, 0, NULL, 6);
INSERT [dbo].[tlkpEPANETFieldDictionary] ([ID], [TableName_FK], [FieldName], [FieldAlias], [InINP], [FieldINP_Number], [Subtype], [CanBeDV], [FieldClass], [VarOptionList_FK], [IsLookupList], [API_Update], [EPANET_CSharp_LibInt], [RowNo]) VALUES (393, 11, N'Period37Multiplier', N'Period37Multiplier', 1, 2, NULL, 0, 4, 0, 0, 0, NULL, 7);
INSERT [dbo].[tlkpEPANETFieldDictionary] ([ID], [TableName_FK], [FieldName], [FieldAlias], [InINP], [FieldINP_Number], [Subtype], [CanBeDV], [FieldClass], [VarOptionList_FK], [IsLookupList], [API_Update], [EPANET_CSharp_LibInt], [RowNo]) VALUES (394, 11, N'Period38Multiplier', N'Period38Multiplier', 1, 3, NULL, 0, 4, 0, 0, 0, NULL, 7);
INSERT [dbo].[tlkpEPANETFieldDictionary] ([ID], [TableName_FK], [FieldName], [FieldAlias], [InINP], [FieldINP_Number], [Subtype], [CanBeDV], [FieldClass], [VarOptionList_FK], [IsLookupList], [API_Update], [EPANET_CSharp_LibInt], [RowNo]) VALUES (395, 11, N'Period39Multiplier', N'Period39Multiplier', 1, 4, NULL, 0, 4, 0, 0, 0, NULL, 7);
INSERT [dbo].[tlkpEPANETFieldDictionary] ([ID], [TableName_FK], [FieldName], [FieldAlias], [InINP], [FieldINP_Number], [Subtype], [CanBeDV], [FieldClass], [VarOptionList_FK], [IsLookupList], [API_Update], [EPANET_CSharp_LibInt], [RowNo]) VALUES (396, 11, N'Period40Multiplier', N'Period40Multiplier', 1, 5, NULL, 0, 4, 0, 0, 0, NULL, 7);
INSERT [dbo].[tlkpEPANETFieldDictionary] ([ID], [TableName_FK], [FieldName], [FieldAlias], [InINP], [FieldINP_Number], [Subtype], [CanBeDV], [FieldClass], [VarOptionList_FK], [IsLookupList], [API_Update], [EPANET_CSharp_LibInt], [RowNo]) VALUES (397, 11, N'Period41Multiplier', N'Period41Multiplier', 1, 6, NULL, 0, 4, 0, 0, 0, NULL, 7);
INSERT [dbo].[tlkpEPANETFieldDictionary] ([ID], [TableName_FK], [FieldName], [FieldAlias], [InINP], [FieldINP_Number], [Subtype], [CanBeDV], [FieldClass], [VarOptionList_FK], [IsLookupList], [API_Update], [EPANET_CSharp_LibInt], [RowNo]) VALUES (398, 11, N'Period42Multiplier', N'Period42Multiplier', 1, 7, NULL, 0, 4, 0, 0, 0, NULL, 7);
INSERT [dbo].[tlkpEPANETFieldDictionary] ([ID], [TableName_FK], [FieldName], [FieldAlias], [InINP], [FieldINP_Number], [Subtype], [CanBeDV], [FieldClass], [VarOptionList_FK], [IsLookupList], [API_Update], [EPANET_CSharp_LibInt], [RowNo]) VALUES (399, 11, N'Period43Multiplier', N'Period43Multiplier', 1, 2, NULL, 0, 4, 0, 0, 0, NULL, 8);
INSERT [dbo].[tlkpEPANETFieldDictionary] ([ID], [TableName_FK], [FieldName], [FieldAlias], [InINP], [FieldINP_Number], [Subtype], [CanBeDV], [FieldClass], [VarOptionList_FK], [IsLookupList], [API_Update], [EPANET_CSharp_LibInt], [RowNo]) VALUES (400, 11, N'Period44Multiplier', N'Period44Multiplier', 1, 3, NULL, 0, 4, 0, 0, 0, NULL, 8);
INSERT [dbo].[tlkpEPANETFieldDictionary] ([ID], [TableName_FK], [FieldName], [FieldAlias], [InINP], [FieldINP_Number], [Subtype], [CanBeDV], [FieldClass], [VarOptionList_FK], [IsLookupList], [API_Update], [EPANET_CSharp_LibInt], [RowNo]) VALUES (401, 11, N'Period45Multiplier', N'Period45Multiplier', 1, 4, NULL, 0, 4, 0, 0, 0, NULL, 8);
INSERT [dbo].[tlkpEPANETFieldDictionary] ([ID], [TableName_FK], [FieldName], [FieldAlias], [InINP], [FieldINP_Number], [Subtype], [CanBeDV], [FieldClass], [VarOptionList_FK], [IsLookupList], [API_Update], [EPANET_CSharp_LibInt], [RowNo]) VALUES (402, 11, N'Period46Multiplier', N'Period46Multiplier', 1, 5, NULL, 0, 4, 0, 0, 0, NULL, 8);
INSERT [dbo].[tlkpEPANETFieldDictionary] ([ID], [TableName_FK], [FieldName], [FieldAlias], [InINP], [FieldINP_Number], [Subtype], [CanBeDV], [FieldClass], [VarOptionList_FK], [IsLookupList], [API_Update], [EPANET_CSharp_LibInt], [RowNo]) VALUES (403, 11, N'Period47Multiplier', N'Period47Multiplier', 1, 6, NULL, 0, 4, 0, 0, 0, NULL, 8);
INSERT [dbo].[tlkpEPANETFieldDictionary] ([ID], [TableName_FK], [FieldName], [FieldAlias], [InINP], [FieldINP_Number], [Subtype], [CanBeDV], [FieldClass], [VarOptionList_FK], [IsLookupList], [API_Update], [EPANET_CSharp_LibInt], [RowNo]) VALUES (404, 11, N'Period48Multiplier', N'Period48Multiplier', 1, 7, NULL, 0, 4, 0, 0, 0, NULL, 8);


SET IDENTITY_INSERT [tlkpEPANETFieldDictionary] off
Go



Insert Into [dbo].tblVersion (VersionNumber, Description) 
values ('00.01.20a', 'Update for more vartypes for pattern multipliers allowing DVs to reference each individual pattern'); 